cpcds-client-ri/config/routes.rb
################################################################################
#
# Application Routes Configuration
#
# Copyright (c) 2019 The MITRE Corporation.  All rights reserved.
#
################################################################################

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

 
  resources :eobs,            only: [:index, :show]
  resources	:practitioners,		only: [:show]

  get '/home', to: 'welcome#index'
  get '/dashboard', to: 'dashboard#index'
  get '/login', to: 'dashboard#login'
  get '/launch', to: 'dashboard#launch'

  root 'welcome#index'
end

cpcds-client-ri/app/views/partials/_address.html.erb
<tr>
	<td>
	    <% if address.period %>
	     <%= display_raw_date(address.period.start) %> - <%= display_raw_date(address.period.end) %>
		<% else %>
		 "No Period Specified"
		<% end %>
	</td>
	<td>
		<%= link_to google_maps(address), target: '_blank' do %>
		  <% address.line.each do |line| %>
		    <%= sanitize(line) %><br />
		  <% end %>
		  <%= sanitize(address.city) %>, 
		  <%= sanitize(address.state) %> 
		  <%= display_postal_code(address.postalCode) %>
		<% end %>
	</td>
</tr>

cpcds-client-ri/app/views/partials/_footer.html.erb
<footer class='footer mt-auto py-3'>
  <div class='copyright'>
    <p>
    	Icons made by 
    	<a href="https://www.flaticon.com/authors/kiranshastry" title="Kiranshastry">Kiranshastry</a> 
    	from 
    	<a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a>
    </p>
    <p>
      &copy; <%= Time.now.year %> 
      <%= link_to 'The MITRE Corporation', 'https://www.mitre.org' %>. All rights reserved.
    </p>
  </div>
</footer>

cpcds-client-ri/app/views/partials/_head.html.erb
<head>
  <title>Claims and Encounters</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<%= favicon_link_tag asset_path('cpcds.ico') %>
</head>

cpcds-client-ri/app/views/partials/_header.html.erb
<header>
  <nav class='navbar fixed-top navbar-expand-lg bg-dark navbar-dark justify-content-between'>
    <div class='navbar-brand'>
      <%= link_to root_path do %>
		<%= image_tag 'clipboard.svg', id: 'logo', alt: '' %>
        <div class="header-title">Claims and Encounters</div>
      <% end %>
    </div>

    <button class='navbar-toggler' type='button' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>
     <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav mr-auto'>
        <li>
          <%= link_to 'Dashboard', dashboard_path, class: 'nav-link' if !@client.nil? %>
        </li>
        <li>
          <%= link_to 'EOBs', eobs_path, class: 'nav-link' if !@client.nil? %>
        </li>
      </ul>
    </div>
  </nav>
</header>

cpcds-client-ri/app/views/partials/_messages.html.erb
<% if flash.count > 0 %>
	<section class='container messages'>
		<section class='row col-12'>
			<% flash.each do |key, value| %>
				<% if key.is_a?(String) %>
				  <div data-alert class="<%= flash_class(key) %> alert dismissible fade show col-12" role="alert">
				    <%= value %>
						<button type='button' class='close' data-dismiss='alert' aria-label='Close'>
							<span aria-hidden='true'>&times;</span>
						</button>
				  </div>
				<% end %>
			<% end %>
		</section>
	</section>
<% end %>

cpcds-client-ri/app/views/partials/_pagination.html.erb
<div class='btn-group float-right mt-2' role='group'>
  <%= link_to('Previous',
    polymorphic_path(resource, page: 'previous'),
    class: "btn btn-outline-primary #{@previous_page_disabled}")
  %>
  <%= link_to('Next',
    polymorphic_path(resource, page: 'next'),
    class: "btn btn-outline-primary #{@next_page_disabled}")
  %>
</div>

cpcds-client-ri/app/views/partials/_query.html.erb
<% if @search %>
  <div class="row col-12 query">
    Query to server<br />
    <%= @search %>
  </div>
<% end %>