cpcds-client-ri/config/routes.rb
################################################################################
#
# Application Routes Configuration
#
# Copyright (c) 2019 The MITRE Corporation.  All rights reserved.
#
################################################################################

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

 
  resources :eobs,            only: [:index, :show]
  resources	:practitioners,		only: [:show]

  get '/home', to: 'welcome#index'
  get '/dashboard', to: 'dashboard#index'
  get '/login', to: 'dashboard#login'
  get '/launch', to: 'dashboard#launch'

  root 'welcome#index'
end

cpcds-client-ri/app/controllers/welcome_controller.rb
################################################################################
#
# Welcome Controller
#
# Copyright (c) 2020 The MITRE Corporation.  All rights reserved.
#
################################################################################

class WelcomeController < ApplicationController

  def index
    puts "==>WelcomeController.index"
    #reset_session 
#    redirect_to launch_url
  end

end

cpcds-client-ri/app/views/welcome/index.html.erb
<section class='container'>
<h2 class="text-light welcome-text">Connect to a FHIR server</h2>
	<% if @client %>
		<p class="text-success m-auto client-connected" style='text-align: center'>
			Connected to <%= server_url -%>
		</p>
		<p class="text-success m-auto client-connected" style='text-align: center'>
			Patient <%= patient_id -%>
		</p>
	<%else%>
		<p class="text-danger m-auto" style='text-align: center'>No Connection Established</p>
	<% end %>

	<section class='row col-12'>
		<div class='row'>
			<%= form_tag launch_path, method: 'get', class: 'form-inline welcome-form', id: 'server-form' do %>
				<div class='col'></div>
				<div class='form-group col-md-7 last'>
					<label class="float-left"> FHIR Server</label>
					<%= text_field_tag :iss_url, cookies[:iss_url], class: 'form-control',
								placeholder: 'http://cpcds-ri.org/cpcds-server/fhir' %>
					<label class="float-left"> ClientID</label>
					<%= text_field_tag :client_id, cookies[:client_id], class: 'form-control' %>
					<label class="float-left"> Client Secret</label>
					<%= text_field_tag :client_secret, cookies[:client_secret], class: 'form-control' %>
					<%= button_tag 'Connect', class: 'btn btn-primary col-md-2 connect', id: 'server-url' %>
				</div>
				<div class='col'></div>
			<% end %>
		</div>

	</section>
</section>