cpcds-client-ri/config/routes.rb
################################################################################
#
# Application Routes Configuration
#
# Copyright (c) 2019 The MITRE Corporation.  All rights reserved.
#
################################################################################

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

 
  resources :eobs,            only: [:index, :show]
  resources	:practitioners,		only: [:show]

  get '/home', to: 'welcome#index'
  get '/dashboard', to: 'dashboard#index'
  get '/login', to: 'dashboard#login'
  get '/launch', to: 'dashboard#launch'

  root 'welcome#index'
end

cpcds-client-ri/app/models/eob.rb
################################################################################
#
# Patient Model
#
# Copyright (c) 2019 The MITRE Corporation.  All rights reserved.
#
################################################################################

class EOB < Resource

	include ActiveModel::Model
  #-----------------------------------------------------------------------------
  attr_accessor :id, :created, :billingstartdate, :billingenddate, :category, :careteam, :claim_reference, :claim, :facility, :use, :insurer, :provider, 
      :coverage, :items, :fhir_client, :sortDate, :total, :payment, :supportingInfo, :patient,  :payeetype, :payeeparty, :type, :adjudication , :outcome, :use

  def initialize(fhir_client, fhir_eob, patients, practitioners, locations, organizations, coverages, practitionerroles)
    @id = fhir_eob.id
    @type = CLAIM_TYPE_CS[codingToString(fhir_eob.type&.coding)]
    if @type == "Institutional" 
      subtype = CLAIM_SUBTYPE_CS[codingToString(fhir_eob.subType&.coding)]
      @type = "#{@type} (#{subtype})"
    end
    @use = fhir_eob.use
    @patient = patients[0].names 
    @sortDate = DateTime.parse(fhir_eob.created).to_i
    @created = dateToString(fhir_eob.created)
    @billingstartdate = dateToString(fhir_eob.billablePeriod&.start)
    @billingenddate = dateToString(fhir_eob.billablePeriod&.end)
    insurer_id = get_id_from_reference(fhir_eob.insurer.reference)
    i  = elementwithid(organizations, insurer_id)
    @insurer = i ? i : Struct.new(*[:name, :telecoms, :addresses]).new(*['missing', [], []])
    provider_id = get_id_from_reference(fhir_eob.provider.reference)
    p = (elementwithid(practitioners, provider_id) || elementwithid(organizations, provider_id))
    @provider = p ? p : Struct.new(*[:name, :telecoms, :addresses]).new(*['missing', [], []])
    @payeetype = codeable_concept_to_string(fhir_eob.payee&.type)
    payeeparty_id = get_id_from_reference(fhir_eob.payee&.party&.reference)
    @payeeparty = fhir_eob.payee ? (elementwithid(patients, payeeparty_id) || elementwithid(practitioners, payeeparty_id) || elementwithid(organizations, payeeparty_id)) : "none"
    @outcome = fhir_eob.outcome 
=begin  @careteam = fhir_eob.careTeam.each_with_object({}) do |member, hash|
             sequence = member.sequence
             practitioner =  elementwithid( practitioners, member.provider.reference )
             name = practitioner.name[0]
             rendername = name.prefix.join(" ") if name.prefix
             rendername = rendername + " " + name.given.join(" ") + " " + name.family 
             hash[sequence] = { :name => rendername,
                                 :role =>  member.role.coding.map {|coding| coding.display}.join(",")
              }
    end
     @careteam = fhir_eob.careTeam
=end
    if fhir_eob.diagnosis 
      @diagnosis = fhir_eob.diagnosis.each_with_object({}) do |d, hash|
        sequence = d.sequence
        codeable = codingToString(d.diagnosisCodeableConcept.coding)
        type = codingToString(d.type.map(&:coding).flatten)
        hash[sequence]  = {:code => codeable, :type => type}
      end
    end
    
    @facility =  fhir_eob.facility.display  || "<MISSING>"
    @use = fhir_eob.use || "<MISSING>"
    @total =  parseTotal(fhir_eob.total) 
    @payment = fhir_eob.payment && fhir_eob.payment.amount ? amountToString(fhir_eob.payment.amount) : "<MISSING>"  
    @paymenttype= fhir_eob.payment ? codingToString(fhir_eob.payment.type.coding) : "<MISSING>"  
    @paymentdate=  fhir_eob.payment ? dateToString(fhir_eob.payment.date) : "<MISSING>"  
    @supportingInfo = parseSupportingInfo(fhir_eob.supportingInfo, fhir_client)
    coverage_id = get_id_from_reference(fhir_eob.insurance&.first&.coverage&.reference)
    @coverage = elementwithid(coverages,coverage_id)  
    @items = parseItems(fhir_eob.item) if fhir_eob.item 
    @adjudication = parseAdjudication(fhir_eob.adjudication) 
  end

  def parseTotal(total)
    total.map{ |item|
      {
      :category => codeable_concept_to_string(item.category),
      :amount => "$#{item.amount.value}"
      }
    }
  end

  def parseSupportingInfo(supportingInfo, fhir_client)
    hash = {}
    supportingInfoHash = supportingInfo.each_with_object({}) do |member, hash|
      sequence = member.sequence
      category_code = codingToString(member.category.coding)
      category = SUPPORTING_INFO_CS[category_code] ||ADJUDICATION_CS[category_code]
      info = 'missing'
      info = codingToString(member.code.coding) if member.code
      info = "#{ADA_UNIVERSAL_NS[info]} (#{info})" if category == "Additional Body Site"  #TODO: to be revised for all EOB profiles
      info = dateToString(member.timingDate) if member.timingDate
      info = ("#{dateToString(member.timingPeriod.start)} - #{dateToString(member.timingPeriod.end)}") if member.timingPeriod
      info = member.valueBoolean ||member.valueString ||member.valueQuantity&.value || info
      if member.valueReference
        resource = fhir_client.read(nil, member.valueReference.reference).resource
        info = resource.name
      end
      
      hash[sequence] = { :category => category, :info => info.to_s }
    end
    supportingInfoHash.sort_by { |seq, h| seq }.to_h
  end

  def parseAdjudication(adjudication)
    adjudication ||= []

    adjudication.map do |item|
      amount = type = reason = value = 'N/A'
      type = ADJUDICATION_CS[codingToString(item.category.coding)] || type
      amount = amountToString(item.amount)
      reason = item.reason.present? ? codeable_concept_to_string(item.reason) : reason
      value = item.value || value
      {
        :type => type,
        :amount => amount,
        :value => value,
        :reason => reason 
      }
    end
  end

  def parseItems(items)
    items ||= []

    items.map do | item | 
      itemloc = item.locationCodeableConcept.present? ? 
                "#{item.locationCodeableConcept.coding&.first&.display} (#{codingToString(item.locationCodeableConcept.coding)})" 
                : 'N/A'
      itemproductOrService = "#{item.productOrService&.coding&.first&.display} (#{codingToString(item.productOrService&.coding)})"
      itemstartDate = item.servicedDate.present? ? dateToString(item.servicedDate) : @billingstartdate

      itemadjudication = item.adjudication&.map do |adj|  
        value = amountToString(adj.amount) 
        type = ADJUDICATION_CS[codingToString(adj.category.coding)]
        text = adj.category&.text
        adjvalue = {type: type, value: value, text: text}
      end

      revenue = codeable_concept_to_string(item.revenue)
      {
        :revenue => revenue,
        :diagnosisSequence =>item.diagnosisSequence,
        :procedureSequence =>item.procedureSequence,
        :careteamSequence =>item.careTeamSequence,
        :informationSequence =>item.informationSequence,
        :location => itemloc,
        :productOrService => itemproductOrService,
        :startDate => itemstartDate,
        :adjudication => itemadjudication,
        :quantity => item.quantity 
      }
    end
  end

  #-----------------------------------------------------------------------------

  def valueToText(obs)
    value = "nil"
    value = obs.valueBoolean  if obs.valueBoolean
    value = obs.valueCodeableConcept.display if obs.valueCodeableConcept
    value = obs.valueDateTime if obs.valueDateTime
    value = obs.valueInteger if obs.valueInteger
    value = obs.valuePeriod if obs.valuePeriod
    value = sprintf('%.2f',obs.valueQuantity.value) + obs.valueQuantity.unit if obs.valueQuantity 
    value = obs.valueRange if obs.valueRange 
    value = obs.valueRatio if obs.valueRatio
    value = obs.valueSampledData if obs.valueSampledData  
    value = obs.valueString if obs.valueString 
    value = obs.valueTime if obs.valueTime    
  end   

  @@adjudicationToText = {
    "https://bluebutton.cms.gov/resources/variables/line_alowd_chrg_amt" => "2Allowed Charge",
    "https://bluebutton.cms.gov/resources/variables/line_sbmtd_chrg_amt" => "1Submitted Charge",
    "https://bluebutton.cms.gov/resources/variables/line_prvdr_pmt_amt" => "3Paid to Provider",
    "https://bluebutton.cms.gov/resources/variables/line_bene_ptb_ddctbl_amt" => "4You Owe (Deductible)",
    "https://bluebutton.cms.gov/resources/variables/line_coinsrnc_amt" => "5You Owe (Coinsurance)"
  }

end

cpcds-client-ri/app/controllers/eobs_controller.rb
################################################################################
#
# Eobs Controller
#
# Copyright (c) 2020 The MITRE Corporation.  All rights reserved.
#
################################################################################

class EobsController < ApplicationController
  before_action :connect_to_server, only: [ :index, :show ]

  # GET /eobs: show a collection of EOBs
  def index
    # patient_id = session[:patient_id]

    # Factor out initial search for all EOBs for a patient during the last year, or by service-date window if specified 

    eobid = nil 
    @client = FHIR::Client.new(session[:iss_url])
    @client.use_r4
    @client.set_bearer_token(session[:access_token])
    eobid = nil 
    load_fhir_eobs(session[:patient_id], eobid)
    @start_date = start_date
    @end_date = end_date 
  end

  # GET /eobs/[id]: show a single EOB
  def show
    #patient_id = session[:patient_id]
    eob_id = params[:id]
    # Factor out search for an EOB by id with patient id 
    load_fhir_eobs(session[:patient_id], eob_id) 
    @eob = nil
    if @eobs
      @eob = @eobs.select{|p| p.id == eob_id}[0] 
    end
  rescue StandardError => exception
    reset_session
    err = "Failed to connect: " + exception.message
    redirect_to root_path, alert: err
  end

end

cpcds-client-ri/app/helpers/eob_helper.rb
module EobHelper
end

cpcds-client-ri/app/views/eobs/_coverage-card.html.erb
<div class='card bg-dark text-center'>
  <h2 class='card-header'>Coverage Information</h2>
  <div class='card-body'>
    <table class='table table-bordered table-dark status'>
      <thead class='thead-dark'>
      
        <tr>
          <th>Policy Issuer</th>
          <th>Period</th>
          <th>Subscriber ID</th>
          <th>Subscriber relationship</th>
          <th colspan='3' scope='colgroup'>Class</th>
        </tr>
        <tr>
          <td colspan='4'></td>
          <th scope='col'>Name</th>
          <th scope='col'>Type</th>
          <th scope='col'>Identifier</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <% span = @eob.coverage.classes.size %>
          <td rowspan="<%= span %>">
            
            <% @eob.coverage.payors.each do |payor| %>
              <span title="<%= display_contact_info(payor.addresses.first, payor.telecoms)%>" data-toggle='tooltip' data-html='true'>
                <%= sanitize(payor.name) %>
              </span>
            <% end %>
            
          </td>
          <td rowspan="<%= span %>"><%= "#{sanitize(@eob.coverage.period_start)} - #{sanitize(@eob.coverage.period_end)}" %></td>
          <td rowspan="<%= span %>"><%= sanitize(@eob.coverage.subscriberId) %></td>
          <td rowspan="<%= span %>"><%= sanitize(@eob.coverage.relationship) %></td>
          <% @eob.coverage.classes.each_with_index do |cov_class, index| %>
            
            <% if index == 0 %>
              <td scope='rowgroup'><%= sanitize(cov_class.name) %></td>
              <td><%= sanitize(cov_class.type) %></td>
              <td><%= sanitize(cov_class.value) %></td>
            <% else %>
              <tr>
                <td scope='rowgroup'><%= sanitize(cov_class.name) %></td>
                <td><%= sanitize(cov_class.type) %></td>
                <td><%= sanitize(cov_class.value) %></td>
              </tr>
            <% end %>
            
          <% end %>  
        </tr>
      </tbody>
    </table>
  </div>
</div>

cpcds-client-ri/app/views/eobs/_detail-card.html.erb
<div class='card bg-dark text-white text-center'>
  <div class='card-body'>

  <% unless @eob.adjudication.empty? %>
    <div height="500">&nbsp;</div>
    <%= render 'header-level-info' %>
  <% end %>

  <% unless @eob.items.empty? %>
    <%= render 'item-level-info' %>
  <% end %>
    
  <% unless @eob.total.empty? %>
    <div height="500">&nbsp;</div>
    <%= render 'total' %>
  <% end %>
  </div>
</div>

cpcds-client-ri/app/views/eobs/_eob-card.html.erb
<div class='card bg-dark text-white'>
  <div class='card-body'>
    <div class='row patient-info'>
      <div class='col-3'>
        <%= display_photo(@patient.photo, @patient.gender, class: 'profile-photo') %>
      </div>
      <div class='col-9'>
        <table class='table table-striped table-dark status'>
          <tr>
            <th>Patient :</th>
            <td>
              <% @patient.names.each do |name| %>
                <%= display_human_name(name) %><br />
              <% end %>
            </td>        
          </tr>
          <tr>
            <th>EOB Created Date :</th>
            <td><%= sanitize(@eob.created) %></td>        
          </tr>
          <tr>
          <th>Billing Period Date :</th>
          <td><%= sanitize(@eob.billingstartdate) + "-" + sanitize(@eob.billingenddate) %></td>    
          </tr>
          <tr>
            <th>Use :</th>
            <td><%= sanitize(@eob.use)&.capitalize %></td>
          </tr>
          <tr>
            <th>Type :</th>
            <td><%= sanitize(@eob.type) %></td>        
          </tr>
          <tr>
            <th>Outcome</th>
            <td><%= sanitize(@eob.outcome)&.capitalize %></td>
          </tr>
          <tr>
            <th>Provider :</th>
            <% telecoms = address_text(@eob.provider.addresses.first) || "" %>
            <% @eob.provider.telecoms.each do |telecom| %>
              <% telecoms += "</br>" if telecoms.present? %>
              <% telecoms += "<small>#{display_telecom(telecom)}</small>"%>
            <% end %>
            
            <td title="<%=display_contact_info(@eob.provider.addresses.first, @eob.provider.telecoms)%>" 
              data-toggle='tooltip' data-html='true'
            >
              <%= sanitize(@eob.provider.name) %>

            </td>        
          </tr>
          <tr>
            <th>Insurer :</th>
            <td title="<%= display_contact_info(@eob.insurer.addresses.first, @eob.insurer.telecoms) %>"
              data-toggle='tooltip' data-html='true'
            >
              <%= sanitize(@eob.insurer.name) %>
            </td>        
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>

cpcds-client-ri/app/views/eobs/_header-level-info.html.erb
<div class='card bg-dark text-white mb-4'>
  <h2>Header Level Information</h2>
  <table class='table table-striped table-dark status'>
    <colgroup>
          <col style="width:25%">
          <col style="width:25%">
          <col style="width:25%">
          <col style="width:25%">
    </colgroup>
    <thead>
      <tr> 
        <th>Type</th>
        <th>Amount</th>
        <th>Value</th>  
        <th>Reason</th> 
      </tr> 
    </thead>
    </tbody>
      <% @eob.adjudication.each do |item| %> 
        <tr class='eobitem'>
          <td><%= sanitize(item[:type]) %></td>
          <td><%= sanitize(item[:amount]) %></td>
          <td><%= sanitize(item[:value]) %></td>
          <td><%= sanitize(item[:reason]) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

cpcds-client-ri/app/views/eobs/_item-level-info.html.erb
<div class='card bg-dark text-white mb-4'>
  <h2>Item Level Information</h2>
  <table class='table table-striped table-dark status'>
    <colgroup>
      <col style="width: 15%">
      <col style="width: 25%">
      <col style="width: 40%">
      <col style="width: 20%">
    </colgroup>
    <thead>
      <tr> 
        <th>Date</th> 
        <th>Location</th>
        <th>Product/Service</th>
        <th>Revenue</th> 
      </tr> 
    </thead>
    </tbody>
      <% @eob.items.each do |item| %> 
        <tr class='eobitem'>
          <td><%= sanitize(item[:startDate]) %></td>
          <td><%= sanitize(item[:location]) %></td>
          <td>
            <p><%= sanitize(item[:productOrService]) %></p>
            <% if item[:adjudication].length > 0 %>
              <p>Adjudication</p>
              <table class='table table-dark caption-top'>
                <tbody>
                  <% item[:adjudication].each do |adj| %>
                    
                    <% if ['In Network', 'Out of Network', 'Other Network'].include?(adj[:type]) %>
                      <caption><%= sanitize(adj[:type]) %></caption>
                    <% else %>
                      <tr class='adjudication'>
                        <th title='<%= adj[:text]%>' data-toggle='tooltip'><%= sanitize(adj[:type]) %> :</th>
                        <td><%= sanitize(adj[:value]) %></td>
                      </tr>
                    <% end %>
                    
                  <% end %>
                </tbody>
              </table>
            <% end %>
          </td>
          <td><%= sanitize(item[:revenue]) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

cpcds-client-ri/app/views/eobs/_supportinginfo-card.html.erb
<div class='card bg-dark text-center'>
  <h2 class='card-header'>Supporting Information</h2>
  <div class='card-body'>
    <table class='table table-dark table-striped status caption-top'>
      <tbody>
        <% @eob.supportingInfo.each do |sequence, supportingInfo| %>
        
          <% if ['In Network', 'Out of Network', 'Other Network'].include?(supportingInfo[:category]) %>
            <caption><h3><%= sanitize(supportingInfo[:category]) %></h3></caption>
          <% else %>
            <tr>
              <th scope='row'><%= sanitize(supportingInfo[:category]) %>:</th>
              <td><%= sanitize(supportingInfo[:info]) %></td>
            </tr>
          <% end %>
        
        <% end %>
      </tbody>
    </table>
  </div>
</div>

cpcds-client-ri/app/views/eobs/_total.html.erb
<div class='card bg-dark text-white mb-4'>
  <h2>Total</h2>
  <table class='table table-striped table-dark status'>
    <colgroup>
      <col style="width:20%">
      <col style="width:20%">
    </colgroup>
    <thead>
      <tr> 
        <th>Type</th>
        <th>Amount</th>
      </tr> 
    </thead>
    </tbody>
      <% @eob.total.each do |total| %> 
        <tr class='eobtotal'>
          <td><%= sanitize(total[:category]) %></td>
          <td><%= sanitize(total[:amount]) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

cpcds-client-ri/app/views/eobs/index.html.erb
<section class='container'> 
  <section class='row col-12'> 
    <div class='col-12'> 
      <h2 class='text-white'>
        Explanation of Benefits 
        <% if @start_date.present? && @end_date.present? %>
          <%= @start_date %> - <%= @end_date %> 
        <% end %>
      </h2>
      <%= render 'partials/query' %>
      <div class='btn-group float-right mt-2' role='group'> 
      </div> 
    </div> 
    <table class='table table-striped table-dark status'> 
      <thead>
        <tr> 
          <th scope='col'>Billing Period</th>
          <th scope='col'>Date Created</th> 
          <th scope='col'>Type</th> 
          <th scope='col'>Patient Name</th>
          <th scope='col'>Provider Name</th> 
        </tr> 
      </thead>
      <% @eobs.each do |eob| %> 
        <tr> 
          <th scope="row">
           <%= link_to sanitize(eob.billingstartdate) + "-" + sanitize(eob.billingenddate), eob_path(eob.id) %>
          </th>
          <td><%= eob.created %></td>    
          <td> <%= eob.type %></td>
          <td>
            <% @patient.names.each do |name| %>
              <%= display_human_name(name) %><br />
            <% end %>
          </td>
          <td><%= sanitize(eob.provider.name) %></td> 
        </tr> 
      <% end %> 
    </table> 
    <div class='col-12'> 
      <div class='btn-group float-right mt-2' role='group'> 
      </div> 
    </div> 
  </section>
</section>

cpcds-client-ri/app/views/eobs/show.html.erb
<section class='container'>
  <h3>Explanation of Benefit: <%= @eob.id %></h3>
  <%= render 'partials/query' %>  
  <section class='row'>
    <div class='col-12 card-container'>
      <%= render 'eob-card' %>
    </div>
    <div class='col-12 card-container'>
      <%= render 'coverage-card' %>
    </div>
    <div class='col-12 card-container'>
      <%= render 'supportinginfo-card' %>
    </div>
    <div class='col-12 card-container'>
      <%= render 'detail-card' %>
    </div>
    <%# <div class='col-5' id='map'> %>
    <%# </div> %>
  </section>
</section>
 